name: CD Pipeline
on:
  pull_request:
    branches:
      - main
    types:
      - closed
permissions:
  contents: read
  id-token: write
  actions: read
env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: "AWS_ACCOUNT_ID_REDACTED"
jobs:
  ##Only deploy if the PR was merged to Main. Single branch only.
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: hashicorp/setup-terraform@v4.0.1
        # with:
        #   terraform_version: "1.14.6"

      - uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/gh_actions

      - name: Terraform Init
        id: init
        run: terraform init -input=false

      - name: Download tfplan from separate workflow
        uses: dawidd6/action-download-artifact@v24
        with:
          workflow: ci-lint.yml # Name of the workflow file where it was uploaded
          name: ${{ github.event.pull_request.head.sha }}.tfplan
          workflow_conclusion: success
      
      - name: TF Apply Plan File
        run: |
          terraform apply ${{ github.event.pull_request.head.sha }}.tfplan -input=false
