name: CD Pipeline
on:
  pull_request:
    branches:
      - main
    types:
      - closed
permissions:
  contents: read
  id-token: write
  actions: read
env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: "632988741882"
jobs:
  ##Only deploy if the PR was merged to Main. Single branch only.
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:

      - name: Checkout local Git Repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup kubectl
        uses: azure/setup-kubectl@v5.1.0
        # with:
        #   version: '<version>' # default is latest stable

      - name: Assume IAM Role via OIDC
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/gh_actions

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4.0.1
        with:
          terraform_version: "~1.16.1"

      - name: Terraform init
        id: init
        run: |
         terraform init -input=false \
          -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}" \
          -backend-config="key=${{ vars.TF_STATE_KEY }}" \
          -backend-config="region=${{ vars.AWS_REGION }}"

      - name: Download Terraform Plan from PR
        uses: dawidd6/action-download-artifact@v24
        with:
          workflow: ci-lint.yml # Name of the workflow file where it was uploaded
          name: ${{ github.event.pull_request.head.sha }}.tfplan
          workflow_conclusion: success
      
      # - name: Terraform apply 
      #   run: |
      #     terraform apply -input=false ${{ github.event.pull_request.head.sha }}.tfplan
