name: CD Pipeline
on:
  pull_request:
    branches:
      - main
    types:
      - closed
permissions:
  contents: read
  id-token: write
env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: "AWS_ACCOUNT_ID_REDACTED"
jobs:
  ##Only deploy if the PR was merged to Main. Single branch only.
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/gh_actions

      - name: Upload Plan Artifact
        uses: actions/download-artifact@v8.0.1
        with:
          name: ${{ github.event.pull_request.head.sha }}.tfplan
