name: CI [Lint]

on:
  pull_request:

permissions:
  contents: read # for actions/checkout to fetch code
  security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
  actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
  checks: write        # Required to add status summary.
  pull-requests: write # Required to add PR comment.
  id-token: write

jobs:
  ci-lint-and-checks:
    environment: 
      name: prod
      deployment: false #need environment vars/secrets but isn't actually deploying anything
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local Git Repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Assume IAM Role via OIDC
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/gh_actions

      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          # required
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout TF values repo
        uses: actions/checkout@v7.0.1
        with:
          repository: grayburnd/aws-values
          token: ${{ steps.app-token.outputs.token }}
          ref: 'main'
          path: tf-values

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4.0.1
        with:
          terraform_version: "~1.16.1"

      - uses: gitleaks/gitleaks-action@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform init
        id: init
        run: |
         terraform init -input=false \
          -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}" \
          -backend-config="key=${{ vars.TF_STATE_KEY }}" \
          -backend-config="region=${{ vars.AWS_REGION }}" \
          -backend-config="use_lockfile=true"

      - name: Terraform validate
        id: validate
        run: terraform validate -no-color

      - name: (Checkov) Terraform Security Scan
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          # This will add both a CLI output to the console and create a results.sarif file
          # output_format: cli,sarif
          # output_file_path: console,results.sarif
          output_format: cli
          quiet: true # optional: display only failed checks
          skip_check: CKV_AWS_39,CKV_AWS_38,CKV_AWS_124,CKV_AWS_19,CKV_AWS_144,CKV_AWS_18,CKV_AWS_21,CKV_AWS_145,CKV2_AWS_5,CKV2_AWS_11,CKV2_AWS_12,CKV2_AWS_6,CKV2_AWS_19,CKV_AWS_27
          #CKV_AWS_39 = No private VPC Access as part of project
          #CKV_AWS_38 = No private VPC Access as part of project
          #CKV_AWS_124 = Overkill for project
          #CKV_AWS_19 = All Buckets are encrypted at rest by default. Custom CMK not needed for project.
          #CKV_AWS_144 = Overkill for project
          #CKV_AWS_18 = Overkill for project
          #CKV_AWS_21 = Overkill for project
          #CKV_AWS_145 = Overkill for project
          #CKV2_AWS_5 = Karpenter SG is utilized in GitOps pipelines, thus associated at a later stage and not orphaned.
          #CKV2_AWS_11 = Overkill for project
          #CKV2_AWS_12 = Overkill for project
          #CKV2_AWS_6 = S3 Buckets have block public access by default
          #CKV2_AWS_19 = EIP is associated to a NATGW, not an EC2. This is fine...
          #CKV_AWS_27 = SqsManagedSseEnabled: true so thus it is encrypted by default. No CMK needed due to scope of proj.
      # - name: Upload SARIF file
      #   uses: github/codeql-action/upload-sarif@v2
        
      #   # Results are generated only on a success or failure
      #   # this is required since GitHub by default won't run the next step
      #   # when the previous one has failed. Security checks that do not pass will 'fail'.
      #   # An alternative is to add `continue-on-error: true` to the previous step
      #   # Or 'soft_fail: true' to checkov.
      #   if: success() || failure()
      #   with:
      #     sarif_file: results.sarif

      - name: Terraform plan
        id: plan
        run: |
          pwd 
          ls tf-values/
          cat tf-values/${{ vars.ENVIRONMENT }}.tfvars
          terraform plan -no-color -input=false --var-file=tf-values/${{ vars.ENVIRONMENT }}.tfvars -out=${{ github.event.pull_request.head.sha }}.tfplan

      # Consistently named after the PR feature branch's latest commit
      - name: Upload plan Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          path: ${{ github.event.pull_request.head.sha }}.tfplan
          archive: false ##Single file non-archived

