name: Test

on: workflow_dispatch

jobs:
  test:
    environment: 
      name: prod
      deployment: false #need environment vars/secrets but isn't actually deploying anything
    runs-on: ubuntu-latest
    steps:
        - run: |
            DICT=${{ toJSON(vars) }}
            for var in $(${DICT} | jq -r 'to_entries[] | "\(.key)=\(.value)"'); do
              echo "${key}", ${value}
        - run: |
            env