name: Test

on: workflow_dispatch

jobs:
  test:
    environment: 
      name: prod
      deployment: false #need environment vars/secrets but isn't actually deploying anything
    runs-on: ubuntu-latest
    steps:
        - run: |
            cat <<EOF > example.json
            ${{ toJson(vars) }}
            EOF
            # lowercase everything after the TF_VAR_ prefix in each key, then export key=value
            for var in $(cat example.json | jq -r 'to_entries[] | "\(.key[0:7])\(.key[7:] | ascii_downcase)=\(.value)"');
              do echo "$var" >> "$GITHUB_ENV";
            done
        - run: |
            env