name: Test

on: workflow_dispatch

jobs:
  test:
    environment: 
      name: prod
      deployment: false #need environment vars/secrets but isn't actually deploying anything
    runs-on: ubuntu-latest
    steps:
        - run: |
            DICT=${{ toJSON(vars) }}
            QUERY=$(${DICT} | jq -r 'to_entries[] | "\(.key)=\(.value)"')
            echo ${QUERY}
            # for var in $QUERY; do
            #   echo "${var}";
            # done
        - run: |
            env